import path from "node:path";
import { defineConfig } from "@playwright/test";

/**
 * playwright.config.ts — the headless verification harness (ticket T-14).
 *
 * This is the run's own eye on the Trace screen: a real browser, a synthetic
 * camera and a seeded reference, so `/trace/[id]` can be exercised and
 * screenshotted without an iPhone. What it can and cannot prove is written in
 * plain English in README.md ("What the test rig proves, and what it cannot").
 */

/** Not 3000: the harness must never collide with a dev server on the default port. */
const PORT = 3417;

/**
 * The committed fake camera feed, generated by scripts/make-fake-camera.mjs.
 * The same file is decoded and pushed through `getUserMedia` by
 * tests/e2e/fakeCamera.ts — see the long comment at the top of that file for
 * why the switch below is not sufficient on its own on macOS.
 */
const FAKE_CAMERA = path.resolve(__dirname, "tests/e2e/fixtures/fake-camera.y4m");

export default defineConfig({
  testDir: "./tests/e2e",

  // Traces, error screenshots and any other per-test debris. Kept inside
  // artifacts/ so one .gitignore entry covers everything this harness emits,
  // alongside the named screenshots the spec writes to artifacts/ itself.
  outputDir: "artifacts/playwright",

  // Sequential, one worker. This machine has 8GB of RAM and a parallel run
  // would put several Chromium instances and a Next server on it at once;
  // the suite is small enough that serial costs seconds, not minutes.
  fullyParallel: false,
  workers: 1,

  // No retries, deliberately. The overlay gate is the point of this harness —
  // a gate that is allowed a second attempt reports "passed" for a build where
  // the line art reached the screen only once out of two.
  retries: 0,
  forbidOnly: !!process.env.CI,

  timeout: 60_000,
  expect: { timeout: 10_000 },
  reporter: [["list"]],

  use: {
    baseURL: `http://localhost:${PORT}`,
    browserName: "chromium",
    headless: true,
    // SPEC §3: iPhone portrait. 390x844 is the iPhone 12/13/14 CSS viewport.
    viewport: { width: 390, height: 844 },
    // 1, not 2. The gate counts pixels in a screenshot and every threshold in
    // the spec is expressed in CSS pixels; a retina factor would quadruple
    // them and make the numbers in the report meaningless.
    deviceScaleFactor: 1,
    // Belt and braces with --use-fake-ui-for-media-capture: without this the
    // context denies the camera and getUserMedia rejects with NotAllowedError.
    permissions: ["camera"],
    trace: "off",
    video: "off",
    screenshot: "off",
    launchOptions: {
      args: [
        // Serve a synthetic device instead of real hardware, auto-accept the
        // permission prompt, and play the committed clip through it.
        // MEASURED: honoured on Linux CI; silently ignored by Chrome for
        // Testing on macOS, which is why tests/e2e/fakeCamera.ts also shims
        // getUserMedia from the very same file. Kept because they are correct,
        // free, and the belt to that braces.
        "--use-fake-device-for-media-capture",
        "--use-fake-ui-for-media-capture",
        `--use-file-for-fake-video-capture=${FAKE_CAMERA}`,
      ],
    },
  },

  webServer: {
    // A PRODUCTION build, never `next dev`. Two reasons, both load-bearing:
    // public/sw.js only registers in production, so this is the only way the
    // service worker is part of what gets verified; and a dev server
    // recompiles on demand, which turns a screenshot into a race.
    command: `npm run build && npm run start -- -p ${PORT}`,
    url: `http://localhost:${PORT}`,
    // Never adopt a server this run did not build — an already-listening
    // process on 3417 would be serving some earlier commit's bundle.
    reuseExistingServer: false,
    timeout: 180_000,
    stdout: "pipe",
    stderr: "pipe",
  },
});
